# Generated by Django 5.2.5 on 2025-09-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tarefa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data',
        ),
    ]
